version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "CET"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: daily
      time: "16:00"
      timezone: "CET"
    open-pull-requests-limit: 10
