---
name: Release drafter

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions: read-all

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
