---
name: Release drafter

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions: read-all

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@73b95fa1c286dfd6802a4f949b07dad6149f2b0f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
